sections:
  main:
    display: Main
    fields:
      - handle: _branding
        field:
          display: Branding
          type: section
          icon: section
          listable: hidden
          instructions_position: above
          read_only: false
      - handle: logo
        field:
          mode: list
          container: assets
          folder: site
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Logo
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
          validate:
            - required
      - handle: logo_light
        field:
          mode: list
          container: assets
          folder: site
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: "Logo Light"
          type: assets
          icon: assets
          instructions: "Logo to be displayed on dark backgrounds."
          listable: hidden
          instructions_position: above
          validate:
            - required
          read_only: false
      - handle: _defaults
        field:
          display: Defaults
          type: section
          icon: section
          listable: hidden
          instructions_position: above
          read_only: false
      - handle: header_image
        field: common.image
        config:
          display: "Header Image"
          validate:
            - required
            - image
          folder: site
          instructions: "The default header image used in the top section of pages (depending on the page's template). This is only used if the page does not have a featured image set."
