sections:
  main:
    display: Main
    fields:
      -
        handle: logo
        field:
          mode: list
          container: assets
          folder: site
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Logo
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
          validate:
            - required
      -
        handle: logo_light
        field:
          mode: list
          container: assets
          folder: site
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Logo Light'
          type: assets
          icon: assets
          instructions: 'Logo to be displayed on dark backgrounds.'
          listable: hidden
          instructions_position: above
          validate:
            - required
          read_only: false
